trigger:
- main

pool:
  name: Samuel
  demands:
    - Agent.Name -equals sam

variables:
  dockerHubConnection: 'docker'
  imageName: 'samuel2004/periodic_table'

steps:
  - checkout: self

  - script: |
      docker run --rm \
        -v "$(System.DefaultWorkingDirectory):/usr/src" \
        sonarsource/sonar-scanner-cli:5 \
        -Dsonar.projectKey=Periodic-Table \
        -Dsonar.sources=/usr/src \
        -Dsonar.host.url=http://host.docker.internal:9000 \
        -Dsonar.login=squ_01ae9a90f8ff5220f516aaa4bb5beefe1337e238 \
        -Dsonar.scm.disabled=true \
        -Dsonar.branch.name=
    displayName: 'Run SonarScanner in Docker Step'
  
  - task: dependency-check-build-task@6
    inputs:
      projectName: 'Periodic-Table'
      scanPath: '$(System.DefaultWorkingDirectory)'
      format: 'HTML'  # Other options: HTML, XML, JSON, CSV, ALL
    displayName: 'Run OWASP Dependency-Check'
  
  - task: Docker@2
    displayName: 'Build Docker image'
    inputs:
      containerRegistry: $(dockerHubConnection)
      repository: $(imageName)
      command: buildAndPush
      Dockerfile: '**/Dockerfile'
      tags: |
        latest

  - script: |
      curl -i -X POST https://api.render.com/deploy/https://api.render.com/deploy/srv-d1a01iili9vc73ake5gg?key=W8qOTD48rpk
    displayName: 'Trigger Render Deployment (Safe & Logged)'
    condition: succeeded()