trigger:
- main

pool:
  name: Samuel
  demands:
    - Agent.Name -equals sam

variables:
  dockerHubConnection: 'docker'
  imageName: 'samuel2004/periodic_table'

steps:
  - checkout: self

  - script: |
      sonar-scanner \
        -Dsonar.projectKey=Periodic-Table \
        -Dsonar.sources=. \
        -Dsonar.host.url=http://localhost:9000/ \
        -Dsonar.login=squ_01ae9a90f8ff5220f516aaa4bb5beefe1337e238 \
        -Dsonar.scm.disabled=true
    displayName: "Run SonarQube CLI Analysis"
  
  - task: dependency-check-build-task@6
    inputs:
      projectName: 'Periodic-Table'
      scanPath: '$(System.DefaultWorkingDirectory)'
      format: 'HTML'  # Other options: HTML, XML, JSON, CSV, ALL
    displayName: 'Run OWASP Dependency-Check'
  
  - task: Docker@2
    displayName: 'Build Docker image'
    inputs:
      containerRegistry: $(dockerHubConnection)
      repository: $(imageName)
      command: buildAndPush
      Dockerfile: '**/Dockerfile'
      tags: |
        latest

  - script: |
      curl -i -X POST https://api.render.com/deploy/https://api.render.com/deploy/srv-d1a01iili9vc73ake5gg?key=W8qOTD48rpk
    displayName: 'Trigger Render Deployment (Safe & Logged)'
    condition: succeeded()